apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp
  namespace: default
spec:
  secretName: myapp-tls-staging
  issuerRef:
    name: myapp-letsncrypt-staging
  commonName: myapp.overbinary.org
  #dnsNames:
  #- www.myapp.overbinary.org
  acme:
    config:
    - http01:
        ingress: myapp
      domains:
      - myapp.overbinary.org
      #- www.myapp.overbinary.org
